apiVersion: database.zeroinfra.github.com/v1
kind: MongoReplicaSet
metadata:
  labels:
    app.kubernetes.io/name: database-operator
    app.kubernetes.io/managed-by: kustomize
  name: mongoreplicaset-sample
spec:
  # TODO(user): Add fields here
