apiVersion: batch.zeroinfra.github.com/v1
kind: CronJob
metadata:
  labels:
    app.kubernetes.io/name: batch-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-sample
spec:
  # TODO(user): Add fields here
