# This rule is not used by the project database-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over database.zeroinfra.github.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: database-operator
    app.kubernetes.io/managed-by: kustomize
  name: rediscluster-admin-role
rules:
- apiGroups:
  - database.zeroinfra.github.com
  resources:
  - redisclusters
  verbs:
  - '*'
- apiGroups:
  - database.zeroinfra.github.com
  resources:
  - redisclusters/status
  verbs:
  - get
