# This rule is not used by the project storage-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over storage.zeroinfra.github.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: storage-operator
    app.kubernetes.io/managed-by: kustomize
  name: objectstorage-admin-role
rules:
- apiGroups:
  - storage.zeroinfra.github.com
  resources:
  - objectstorages
  verbs:
  - '*'
- apiGroups:
  - storage.zeroinfra.github.com
  resources:
  - objectstorages/status
  verbs:
  - get
