# This rule is not used by the project storage-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the storage.zeroinfra.github.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: storage-operator
    app.kubernetes.io/managed-by: kustomize
  name: objectstorage-editor-role
rules:
- apiGroups:
  - storage.zeroinfra.github.com
  resources:
  - objectstorages
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - storage.zeroinfra.github.com
  resources:
  - objectstorages/status
  verbs:
  - get
