# This rule is not used by the project batch-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the batch.zeroinfra.github.com.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: batch-operator
    app.kubernetes.io/managed-by: kustomize
  name: cronjob-editor-role
rules:
- apiGroups:
  - batch.zeroinfra.github.com
  resources:
  - cronjobs
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - batch.zeroinfra.github.com
  resources:
  - cronjobs/status
  verbs:
  - get
