# This rule is not used by the project batch-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants read-only access to batch.zeroinfra.github.com resources.
# This role is intended for users who need visibility into these resources
# without permissions to modify them. It is ideal for monitoring purposes and limited-access viewing.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: batch-operator
    app.kubernetes.io/managed-by: kustomize
  name: workflow-viewer-role
rules:
- apiGroups:
  - batch.zeroinfra.github.com
  resources:
  - workflows
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - batch.zeroinfra.github.com
  resources:
  - workflows/status
  verbs:
  - get
