# This rule is not used by the project batch-operator itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants full permissions ('*') over batch.zeroinfra.github.com.
# This role is intended for users authorized to modify roles and bindings within the cluster,
# enabling them to delegate specific permissions to other users or groups as needed.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: batch-operator
    app.kubernetes.io/managed-by: kustomize
  name: workflow-admin-role
rules:
- apiGroups:
  - batch.zeroinfra.github.com
  resources:
  - workflows
  verbs:
  - '*'
- apiGroups:
  - batch.zeroinfra.github.com
  resources:
  - workflows/status
  verbs:
  - get
