# This kustomization.yaml is not intended to be run by itself,
# since it depends on service name and namespace that are out of this kustomize package.
# It should be run by config/default
resources:
- bases/model.zeroinfra.github.com_models.yaml
- bases/model.zeroinfra.github.com_datasets.yaml
- bases/model.zeroinfra.github.com_inferences.yaml
- bases/model.zeroinfra.github.com_trainings.yaml
- bases/model.zeroinfra.github.com_finetunings.yaml
# +kubebuilder:scaffold:crdkustomizeresource

patches:
# [WEBHOOK] To enable webhook, uncomment all the sections with [WEBHOOK] prefix.
# patches here are for enabling the conversion webhook for each CRD
# +kubebuilder:scaffold:crdkustomizewebhookpatch

# [WEBHOOK] To enable webhook, uncomment the following section
# the following config is for teaching kustomize how to do kustomization for CRDs.
#configurations:
#- kustomizeconfig.yaml
